"""End-to-end ingest test against real ffmpeg/ffprobe.

Skipped when ffmpeg/ffprobe are not installed (this sandbox has neither --
see docs/status.md). Uses a synthetically generated clip rather than a real
Insta360 X6 export; open question in the handover doc, section 12, asks
whether a small redistributable reference dataset can be committed instead.
"""

import subprocess

import pytest

from conftest import requires_ffmpeg

from vine360.config import CaptureMode, MediaType
from vine360.ingest.frames import extract_frames
from vine360.ingest.manifest import build_manifest
from vine360.ingest.sources import add_source
from vine360.project import create_project, open_index_db
from vine360.runners.local import LocalRunner


def _make_synthetic_clip(path, duration=4, width=640, height=320):
    # width:height = 2:1 to exercise the equirectangular-detection path,
    # mirroring an Insta360 X6 equirectangular export's aspect ratio.
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"testsrc=duration={duration}:size={width}x{height}:rate=10",
            str(path),
        ],
        check=True,
        capture_output=True,
    )


@requires_ffmpeg
def test_ingest_and_extract_frames_end_to_end(tmp_path):
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()

    source = add_source(
        conn,
        clip_path,
        runner,
        media_type_override=MediaType.VIDEO,
        added_at="2026-01-01T00:00:00+00:00",
    )
    assert source.timestamps["duration_seconds"] > 0

    frames = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=1.0)
    assert len(frames) >= 3
    for i, frame in enumerate(frames):
        assert (project_root / frame.path).exists()
        assert frame.source_time == i * 1.0
        assert frame.frame_set_id == f"{source.source_id}~i1"

    thumbs_dir = project_root / "frames" / frames[0].frame_set_id / "thumbs"
    assert list(thumbs_dir.glob("*.jpg")), "thumbnails should still be generated by default"

    manifest = build_manifest(conn)
    assert manifest["source_frame_map"][source.source_id] == [f.frame_id for f in frames]
    conn.close()


@requires_ffmpeg
def test_extract_frames_can_skip_thumbnail_generation(tmp_path):
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()

    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    frames = extract_frames(
        conn, project_root, source.source_id, runner, interval_seconds=1.0, generate_thumbnails=False
    )
    assert len(frames) >= 3
    for frame in frames:
        assert (project_root / frame.path).exists()  # the frame itself is still written

    thumbs_dir = project_root / "frames" / frames[0].frame_set_id / "thumbs"
    assert not thumbs_dir.exists() or not list(thumbs_dir.glob("*.jpg"))
    conn.close()


@requires_ffmpeg
def test_extract_frames_with_time_range_offsets_source_time(tmp_path):
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path, duration=4)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()

    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    whole = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=1.0)
    ranged = extract_frames(
        conn, project_root, source.source_id, runner, interval_seconds=1.0, start_time=1.0, end_time=3.0
    )

    assert len(ranged) < len(whole)  # ~2s window, not ~4s
    assert ranged[0].source_time == pytest.approx(1.0, abs=0.01)
    conn.close()


@requires_ffmpeg
def test_different_intervals_become_separate_frame_sets_side_by_side(tmp_path):
    """docs/adr/0034: extracting a source at a second interval used to
    replace the first extraction outright -- now each config is its own
    frame set, kept alongside the source's others."""
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path, duration=4)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()

    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    first = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=0.5)
    second = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=2.0)

    assert len(first) > len(second)  # smaller interval -> more frames
    assert first[0].frame_set_id != second[0].frame_set_id
    for frames in (first, second):
        frames_dir = project_root / "frames" / frames[0].frame_set_id
        assert len(sorted(frames_dir.glob("frame_*.png"))) == len(frames)
        rows = conn.execute("SELECT COUNT(*) FROM frames WHERE frame_set_id = ?", (frames[0].frame_set_id,))
        assert rows.fetchone()[0] == len(frames)
    labels = [r[0] for r in conn.execute("SELECT label FROM frame_sets ORDER BY label")]
    assert labels == ["every 0.5s", "every 2s"]
    conn.close()


@requires_ffmpeg
def test_re_extracting_the_same_config_replaces_only_that_frame_set(tmp_path):
    """Regression test: re-running an extraction used to fail with a sqlite
    UNIQUE constraint error on frame_id, and could leave stale files behind
    from an earlier, larger extraction. The same config now replaces just
    its own frame set (same id), leaving sibling frame sets alone."""
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path, duration=4)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()
    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    sibling = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=2.0)
    first = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=1.0)
    frames_dir = project_root / "frames" / first[0].frame_set_id
    stale = frames_dir / "frame_999999.png"
    stale.write_bytes(b"left over from a bigger earlier run")

    again = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=1.0)

    assert again[0].frame_set_id == first[0].frame_set_id
    assert not stale.exists()
    assert len(sorted(frames_dir.glob("frame_*.png"))) == len(again)
    assert conn.execute("SELECT COUNT(*) FROM frame_sets").fetchone()[0] == 2
    sibling_count = conn.execute(
        "SELECT COUNT(*) FROM frames WHERE frame_set_id = ?", (sibling[0].frame_set_id,)
    ).fetchone()[0]
    assert sibling_count == len(sibling)
    conn.close()


@requires_ffmpeg
def test_extract_frames_reports_progress(tmp_path):
    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path, duration=3)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()
    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    events = []
    frames = extract_frames(
        conn,
        project_root,
        source.source_id,
        runner,
        interval_seconds=1.0,
        progress_callback=lambda m, c, t: events.append((m, c, t)),
        poll_interval_seconds=0.001,  # tiny, so the raw-extraction poller fires even on this fast synthetic clip
    )
    messages = [m for m, _, _ in events]
    assert any("Extracting raw frames" in m for m in messages)
    assert any("Generating thumbnails" in m for m in messages)
    assert any(f"({len(frames)}/{len(frames)})" in m for m in messages), "should report reaching the last frame"

    extraction_events = [(c, t) for m, c, t in events if m.startswith("Extracting raw frames") and c is not None]
    assert extraction_events, (
        "the raw ffmpeg extraction call previously reported zero progress at all for however long it took"
    )
    assert all(t == extraction_events[0][1] for _, t in extraction_events)  # expected total stays constant
    thumbnail_events = [(c, t) for m, c, t in events if "Generating thumbnails" in m]
    assert thumbnail_events[-1] == (len(frames), len(frames))
    conn.close()


@requires_ffmpeg
def test_re_extracting_frames_cascades_to_views_and_masks(tmp_path):
    """Regression test: re-extracting frames used to leave any views/masks
    built from the *old* frames as orphans (dangling frame_id references,
    stale projections/ directories) -- clear_frame_set must cascade the
    same way clear_views_for_frame already does for a single frame, mask
    files included, and only within the re-extracted frame set."""
    from vine360.masking.build import build_mask_for_view
    from vine360.projection.generate import generate_views_for_frame

    clip_path = tmp_path / "source_clip.mp4"
    _make_synthetic_clip(clip_path, duration=4)

    project_root = tmp_path / "project"
    create_project(project_root, "Integration Test Vineyard", CaptureMode.THREE_SIXTY)
    conn = open_index_db(project_root)
    runner = LocalRunner()
    source = add_source(
        conn, clip_path, runner, media_type_override=MediaType.VIDEO, added_at="2026-01-01T00:00:00+00:00"
    )

    first_frames = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=0.5)
    sibling_frames = extract_frames(conn, project_root, source.source_id, runner, interval_seconds=2.0)
    first_frame_id = first_frames[0].frame_id
    views = generate_views_for_frame(conn, project_root, first_frame_id, face_size=32)
    build_mask_for_view(conn, project_root, views[0].view_id)
    sibling_views = generate_views_for_frame(conn, project_root, sibling_frames[0].frame_id, face_size=32)

    old_projections_dir = project_root / "projections" / first_frame_id
    old_keep_dir = project_root / "masks" / "keep" / first_frame_id
    old_classes_dir = project_root / "masks" / "classes" / views[0].view_id
    assert old_projections_dir.exists() and old_keep_dir.exists() and old_classes_dir.exists()

    extract_frames(conn, project_root, source.source_id, runner, interval_seconds=0.5)

    remaining = {r[0] for r in conn.execute("SELECT view_id FROM views")}
    assert remaining == {v.view_id for v in sibling_views}  # the sibling frame set's views survive
    assert conn.execute("SELECT COUNT(*) FROM masks").fetchone()[0] == 0
    assert not old_projections_dir.exists()
    assert not old_keep_dir.exists()
    assert not old_classes_dir.exists()
    conn.close()
